#!/bin/bash

#creating new users
sudo adduser hod
sudo adduser prof1
sudo adduser prof2
sudo adduser student1
sudo adduser student2
sudo adduser student3
sudo adduser student4
sudo adduser student5
sudo adduser student6
sudo adduser student7
sudo adduser student8
sudo adduser student9
sudo adduser student10
sudo adduser student11
sudo adduser student12
sudo adduser student13
sudo adduser student14
sudo adduser student15
sudo adduser student16
sudo adduser student17
sudo adduser student18
sudo adduser student19
sudo adduser student20
#modifying acces permissions
sudo chmod 777 /home/prof1
sudo chmod 777 /home/prof2
sudo chmod 777 /home/student1
sudo chmod 777 /home/student2
sudo chmod 777 /home/student3
sudo chmod 777 /home/student4
sudo chmod 777 /home/student5
sudo chmod 777 /home/student6
sudo chmod 777 /home/student7
sudo chmod 777 /home/student8
sudo chmod 777 /home/student9
sudo chmod 777 /home/student10
sudo chmod 777 /home/student11
sudo chmod 777 /home/student12
sudo chmod 777 /home/student13
sudo chmod 777 /home/student14
sudo chmod 777 /home/student15
sudo chmod 777 /home/student16
sudo chmod 777 /home/student17
sudo chmod 777 /home/student18
sudo chmod 777 /home/student19
sudo chmod 777 /home/student20
#adding required files and directories for professors
cd /home/prof1
mkdir Teaching_Material
cd /home/prof1/Teaching_Material
touch q1.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q1.txt
touch q2.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q2.txt
touch q3.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q3.txt
touch q4.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q4.txt
touch q5.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q5.txt
touch q6.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q6.txt
touch q7.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q7.txt
touch q8.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q8.txt
touch q9.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q9.txt
touch q10.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q10.txt
touch q11.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q11.txt
touch q12.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q12.txt
touch q13.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q13.txt
touch q14.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q14.txt
touch q15.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q15.txt
touch q16.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q16.txt
touch q17.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q17.txt
touch q18.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q18.txt
touch q19.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q19.txt
touch q20.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q20.txt
touch q21.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q21.txt
touch q22.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q22.txt
touch q23.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q23.txt
touch q24.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q24.txt
touch q25.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q25.txt
touch q26.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q26.txt
touch q27.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q27.txt
touch q28.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q28.txt
touch q29.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q29.txt
touch q30.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q30.txt
touch q31.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q31.txt
touch q32.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q32.txt
touch q33.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q33.txt
touch q34.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q34.txt
touch q35.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q35.txt
touch q36.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q36.txt
touch q37.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q37.txt
touch q38.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q38.txt
touch q39.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q39.txt
touch q40.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q40.txt
touch q41.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q41.txt
touch q42.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q42.txt
touch q43.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q43.txt
touch q44.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q44.txt
touch q45.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q45.txt
touch q46.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q46.txt
touch q47.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q47.txt
touch q48.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q48.txt
touch q49.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q49.txt
touch q50.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q50.txt
cd /home/prof2
mkdir Teaching_Material
cd /home/prof2/Teaching_Material
touch q1.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q1.txt
touch q2.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q2.txt
touch q3.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q3.txt
touch q4.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q4.txt
touch q5.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q5.txt
touch q6.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q6.txt
touch q7.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q7.txt
touch q8.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q8.txt
touch q9.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q9.txt
touch q10.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q10.txt
touch q11.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q11.txt
touch q12.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q12.txt
touch q13.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q13.txt
touch q14.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q14.txt
touch q15.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q15.txt
touch q16.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q16.txt
touch q17.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q17.txt
touch q18.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q18.txt
touch q19.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q19.txt
touch q20.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q20.txt
touch q21.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q21.txt
touch q22.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q22.txt
touch q23.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q23.txt
touch q24.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q24.txt
touch q25.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q25.txt
touch q26.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q26.txt
touch q27.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q27.txt
touch q28.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q28.txt
touch q29.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q29.txt
touch q30.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q30.txt
touch q31.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q31.txt
touch q32.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q32.txt
touch q33.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q33.txt
touch q34.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q34.txt
touch q35.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q35.txt
touch q36.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q36.txt
touch q37.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q37.txt
touch q38.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q38.txt
touch q39.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q39.txt
touch q40.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q40.txt
touch q41.txtcd
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q41.txt
touch q42.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q42.txt
touch q43.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q43.txt
touch q44.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q44.txt
touch q45.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q45.txt
touch q46.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q46.txt
touch q47.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q47.txt
touch q48.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q48.txt
touch q49.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q49.txt
touch q50.txt
< /dev/urandom tr -dc "[:alnum:]" | head -c100 > q50.txt
#creating required directories and files for students
#adding questions 
cd /home/student1
mkdir HomeWork
cd /home/student1/HomeWork
mkdir prof1_work
mkdir prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student1/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student1/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student1/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student1/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student1/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student1/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student1/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student1/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student1/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student1/HomeWork/prof2_work
cd /home/student2
mkdir HomeWork
cd /home/student2/HomeWork
mkdir prof1_work
mkdir prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student2/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student2/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student2/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student2/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student2/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student2/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student2/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student2/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student2/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student2/HomeWork/prof2_work
cd /home/student3
mkdir HomeWork
cd /home/student3/HomeWork
mkdir prof1_work
mkdir prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student3/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student3/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student3/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student3/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student3/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student3/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student3/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student3/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student3/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student3/HomeWork/prof2_work
cd /home/student4
mkdir HomeWork
cd /home/student4/HomeWork
mkdir prof1_work
mkdir prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student4/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student4/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student4/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student4/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student4/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student4/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student4/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student4/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student4/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student4/HomeWork/prof2_work
cd /home/student5
mkdir HomeWork
cd /home/student5/HomeWork
mkdir prof1_work
mkdir prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student5/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student5/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student5/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student5/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student5/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student5/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student5/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student5/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student5/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student5/HomeWork/prof2_work
cd /home/student6
mkdir HomeWor5
cd /home/student6/HomeWork
mkdir prof1_work
mkdir prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student6/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student6/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student6/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student6/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student6/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student6/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student6/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student6/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student6/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student6/HomeWork/prof2_work
cd /home/student7
mkdir HomeWork
cd /home/student7/HomeWork
mkdir prof1_work
mkdir prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student7/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student7/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student7/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student7/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student7/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student7/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student7/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student7/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student7/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student7/HomeWork/prof2_work
cd /home/student8
mkdir HomeWork
cd /home/student8/HomeWork
mkdir prof1_work
mkdir prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student8/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student8/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student8/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student8/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student8/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student8/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student8/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student8/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student8/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student8/HomeWork/prof2_work
cd /home/student9
mkdir HomeWork
cd /home/student9/HomeWork
mkdir prof1_work
mkdir prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student9/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student9/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student9/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student9/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student9/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student9/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student9/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student9/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student9/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student9/HomeWork/prof2_work
cd /home/student10
mkdir HomeWork
cd /home/student10/HomeWork
mkdir prof1_work
mkdir prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student10/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student10/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student10/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student10/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student10/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student10/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student10/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student10/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student10/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student10/HomeWork/prof2_work
cd /home/student11
mkdir HomeWork
cd /home/student11/HomeWork
mkdir prof1_work
mkdir prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student11/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student11/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student11/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student11/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student11/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student11/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student11/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student11/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student11/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student11/HomeWork/prof2_work
cd /home/student12
mkdir HomeWork
cd /home/student12/HomeWork
mkdir prof1_work
mkdir prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student12/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student12/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student12/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student12/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student12/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student12/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student12/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student12/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student12/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student12/HomeWork/prof2_work
cd /home/student13
mkdir HomeWork
cd /home/student13/HomeWork
mkdir prof1_work
mkdir prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student13/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student13/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student13/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student13/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student13/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student13/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student13/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student13/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student13/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student13/HomeWork/prof2_work
cd /home/student14
mkdir HomeWork
cd /home/student14/HomeWork
mkdir prof1_work
mkdir prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student14/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student14/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student14/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student14/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student14/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student14/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student14/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student14/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student14/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student14/HomeWork/prof2_work
cd /home/student15
mkdir HomeWork
cd /home/student15/HomeWork
mkdir prof1_work
mkdir prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student15/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student15/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student15/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student15/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student15/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student15/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student15/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student15/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student15/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student15/HomeWork/prof2_work
cd /home/student16
mkdir HomeWork
cd /home/student16/HomeWork
mkdir prof1_work
mkdir prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student16/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student16/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student16/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student16/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student16/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student16/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student16/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student16/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student16/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student16/HomeWork/prof2_work
cd /home/student17
mkdir HomeWork
cd /home/student17/HomeWork
mkdir prof1_work
mkdir prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student17/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student17/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student17/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student17/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student17/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student17/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student17/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student17/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student17/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student17/HomeWork/prof2_work
cd /home/student18
mkdir HomeWork
cd /home/student18/HomeWork
mkdir prof1_work
mkdir prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student18/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student18/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student18/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student18/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student18/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student18/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student18/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student18/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student18/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student18/HomeWork/prof2_work
cd /home/student19
mkdir HomeWork
cd /home/student19/HomeWork
mkdir prof1_work
mkdir prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student19/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student19/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student19/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student19/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student19/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student19/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student19/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student19/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student19/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student19/HomeWork/prof2_work
cd /home/student20
mkdir HomeWork
cd /home/student20HomeWork
mkdir prof1_work
mkdir prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student20/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student20/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student20/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student20/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof1/Teaching_Material/q$n.txt /home/student20/HomeWork/prof1_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student20/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student20/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student20/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student20/HomeWork/prof2_work
n=$(shuf -i 1-50 -n 1)
cp /home/prof2/Teaching_Material/q$n.txt /home/student20/HomeWork/prof2_work
#giving hod root access 
sudo visudo
#setting access permissions
sudo chmod 700 /home/student1
sudo setfacl -m u:hod:rwx /home/student1
sudo setfacl -m u:prof1:rwx /home/student1
sudo setfacl -m u:prof2:rwx /home/student1
sudo chmod 700 /home/student2
sudo setfacl -m u:hod:rwx /home/student2
sudo setfacl -m u:prof1:rwx /home/student2
sudo setfacl -m u:prof2:rwx /home/student2
sudo chmod 700 /home/student3
sudo setfacl -m u:hod:rwx /home/student3
sudo setfacl -m u:prof1:rwx /home/student3
sudo setfacl -m u:prof2:rwx /home/student3
sudo chmod 700 /home/student4
sudo setfacl -m u:hod:rwx /home/student4
sudo setfacl -m u:prof1:rwx /home/student4
sudo setfacl -m u:prof2:rwx /home/student4
sudo chmod 700 /home/student5
sudo setfacl -m u:hod:rwx /home/student5
sudo setfacl -m u:prof1:rwx /home/student5
sudo setfacl -m u:prof2:rwx /home/student5
sudo chmod 700 /home/student6
sudo setfacl -m u:hod:rwx /home/student6
sudo setfacl -m u:prof1:rwx /home/student6
sudo setfacl -m u:prof2:rwx /home/student6
sudo chmod 700 /home/student7
sudo setfacl -m u:hod:rwx /home/student7
sudo setfacl -m u:prof1:rwx /home/student7
sudo setfacl -m u:prof2:rwx /home/student7
sudo chmod 700 /home/student8
sudo setfacl -m u:hod:rwx /home/student8
sudo setfacl -m u:prof1:rwx /home/student8
sudo setfacl -m u:prof2:rwx /home/student8
sudo chmod 700 /home/student9
sudo setfacl -m u:hod:rwx /home/student9
sudo setfacl -m u:prof1:rwx /home/student9
sudo setfacl -m u:prof2:rwx /home/student9
sudo chmod 700 /home/student10
sudo setfacl -m u:hod:rwx /home/student10
sudo setfacl -m u:prof1:rwx /home/student10
sudo setfacl -m u:prof2:rwx /home/student10
sudo chmod 700 /home/student11
sudo setfacl -m u:hod:rwx /home/student11
sudo setfacl -m u:prof1:rwx /home/student11
sudo setfacl -m u:prof2:rwx /home/student11
sudo chmod 700 /home/student12
sudo setfacl -m u:hod:rwx /home/student12
sudo setfacl -m u:prof1:rwx /home/student12
sudo setfacl -m u:prof2:rwx /home/student12
sudo chmod 700 /home/student13
sudo setfacl -m u:hod:rwx /home/student13
sudo setfacl -m u:prof1:rwx /home/student13
sudo setfacl -m u:prof2:rwx /home/student13
sudo chmod 700 /home/student14
sudo setfacl -m u:hod:rwx /home/student14
sudo setfacl -m u:prof1:rwx /home/student14
sudo setfacl -m u:prof2:rwx /home/student14
sudo chmod 700 /home/student15
sudo setfacl -m u:hod:rwx /home/student15
sudo setfacl -m u:prof1:rwx /home/student15
sudo setfacl -m u:prof2:rwx /home/student15
sudo chmod 700 /home/student16
sudo setfacl -m u:hod:rwx /home/student16
sudo setfacl -m u:prof1:rwx /home/student16
sudo setfacl -m u:prof2:rwx /home/student16
sudo chmod 700 /home/student17
sudo setfacl -m u:hod:rwx /home/student17
sudo setfacl -m u:prof1:rwx /home/student17
sudo setfacl -m u:prof2:rwx /home/student17
sudo chmod 700 /home/student18
sudo setfacl -m u:hod:rwx /home/student18
sudo setfacl -m u:prof1:rwx /home/student18
sudo setfacl -m u:prof2:rwx /home/student18
sudo chmod 700 /home/student19
sudo setfacl -m u:hod:rwx /home/student19
sudo setfacl -m u:prof1:rwx /home/student19
sudo setfacl -m u:prof2:rwx /home/student19
sudo chmod 700 /home/student20
sudo setfacl -m u:hod:rwx /home/student20
sudo setfacl -m u:prof1:rwx /home/student20
sudo setfacl -m u:prof2:rwx /home/student20
sudo chmod 700 /home/prof1
sudo setfacl -m u:hod:rwx /home/prof1
sudo chmod 700 /home/prof2
sudo setfacl -m u:hod:rwx /home/prof2









